fix & tests
mate-academy/qa_restore-names pull request #99
Opened 2024-04-14 09:41 UTC by TykhonKozachenko

2024-04-14 16:23 UTC, PolinaRomanenko requested changes
please, make changes according to the comments)

2024-04-14 16:23 UTC, PolinaRomanenko commented on src/restoreNames.test.js
> +  it('should handle users without fullName', () => {
There is no such specification, that the fullName can be absent. The task states that all the users have fullName, and the firstName may be absent, or undefined. So please, delete unnecessary tests)

2024-04-14 16:23 UTC, PolinaRomanenko commented on src/restoreNames.test.js
> +  it('sets correct first names for users with firstName as undefined', () => {
we can better call this check as 'should work with 2 elements', but also we need to separately check each case - when the firstName is undefined(please, pass only one object into the array for a check), and when the firstName is omitted(also pass only one object into the array for a check)

2024-04-14 17:16 UTC, TykhonKozachenko commented on src/restoreNames.test.js
> +  it('sets correct first names for users with firstName as undefined', () => {
divided into 2 separate tests for convenience

2024-04-15 12:51 UTC, 4ksandrey approved these changes
Accepted, well done

2025-05-13 18:22 UTC, closed without merging